services:
  redis:
    image: "redis:latest"
    container_name: "redis-fade-comment"
    restart: unless-stopped
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - fade-comment-redis-d:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

volumes:
  fade-comment-redis-d: